catergories = [
    'Art Supplies',
    'Baby Gear',
    'Beauty Products',
    'Books and Magazines',
    'Cameras and Photography',
    'Car Accessories',
    'Outdoor Recreation',
    'Computers and Electronics',
    'Crafts and Hobbies',
    'Education and Learning',
    'Exercise and Fitness',
    'Food and Cooking',
    'Furniture and Decor',
    'Gaming and Entertainment',
    'Garden and Outdoor',
    'Health and Wellness',
    'Home Appliances',
    'Home Improvement',
    'Industrial and Scientific',
    'Jewelry and Accessories',
    'Kitchen Appliances',
    'Clothing',
    'Music and Instruments',
    'Office Supplies',
    'Party Supplies',
    'Pet Supplies',
    'Sports and Outdoors',
    'Stationery and Paper Goods',
    'Toys and Games',
    'Travel and Luggage',
    'Video Games and Consoles',
    'Watches and Clocks',
    'Party and Event Supplies',
    'Art and Decor',
    'Baby Clothing and Accessories',
    'Bath and Body',
    'Bedding and Linens',
    'Board Games and Puzzles',
    'Business and Finance',
    'Cell Phones and Accessories',
    'Cleaning and Organization',
    'Clothing Accessories',
    'Collectibles and Memorabilia',
    'Electronic Accessories',
    'Fashion and Accessories',
    'Gourmet Food and Drinks',
    'Hair Care and Styling',
    'Handbags and Wallets',
    'Lighting and Electrical',
    'Musical Accessories']

expenditures =[
    'Rent or Mortgage',
    'Utilities',
    'Groceries',
    'Dining Out',
    'Transportation',
    'Insurance',
    'Health Care Expenses',
    'Clothing and Accessories',
    'Personal Care Products and Services',
    'Entertainment',
    'Travel',
    'Charitable Donations',
    'Home Improvement and Maintenance',
    'Electronics and Technology',
    'Gifts and Celebrations',
    'Education and Training',
    'Pet Care',
    'Savings and Investments',
    'Taxes',
    'Retirement Savings',
    'Recreation and Hobbies',
    'Subscriptions and Memberships',
    'Childcare and Education Expenses',
    'Debt Repayment',
    'Home Furnishings and Decor',
    'Vehicle Expenses',
    'Professional Services',
    'Fitness and Wellness',
    'Home Security and Safety',
    'Internet and Cable',
    'Phone and Mobile Devices',
    'Home Cleaning and Maintenance Services',
    'Home and Garden Supplies',
    'Alcohol and Tobacco',
    'Business Expenses',
    'Gifts for Friends and Family',
    'Fees and Charges',
    'Jewelry and Accessories',
    'Loans and Interest Payments',
    'Office Supplies and Equipment',
    'Personal Development',
    'Photography and Art Supplies',
    'Renters Insurance',
    'Restaurant Delivery Services',
    'School Supplies and Textbooks',
    'Socializing and Nightlife',
    'Sporting Goods and Equipment',
    'Storage and Organization',
    'Taxes and Accounting Services',
    'Tickets for Events and Shows'
]

notificationTitles=[
    'House points lost!',
    'House points gained!',
    'Points lost!',
    'Points gained!',
    'Follow request accepted'
]

notificationMessages=[
    '5 points lost',
    '10 points gained',
    '3 points lost',
    '5 points gained',
    'user123 has accepted your request'
]