# Generated by Django 4.1.4 on 2023-02-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='isSeen',
            field=models.BooleanField(default=False),
        ),
    ]
